config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints(host: ENV['STELLAR_HOST']) do
    resource :onboarding do
      get :frontend
      get :backend
      get :admin
      post 'validate/:step', action: :validate, as: :validate
    end
    get '/', to: 'account#index'
    get '/get-started', to: 'account#onboarding', as: :get_started
  end

  root 'store#index'

  # Catch error conditions early.
  match '(errors)/:status', to: 'errors#show',
    constraints: {status: /\d{3}/},
    defaults: {status: '500'},
    via: :all

  # Point-of-sale interface.
  #namespace :pos do
  #  root 'main#index'
  #  resources :orders do
  #    resources :order_items, shallow: true
  #  end
  #  resources :products do
  #    get :query, on: :collection
  #  end
  #end

  # Mount stripe engine at /stripe
  mount Stripe::Engine => '/stripe'

  resources :orders do
    resources :order_items, shallow: true
    member do
      get :select
      get :preview
      patch :claim
      get :duplicate
    end
  end
  resource :profile, only: [:show, :edit, :update]

  # Catch bona fide storefront urls that are not accessible via slugs.
  get  '/store', to: 'store#index', as: :store
  get  '/store/lookup', to: 'store#lookup', as: :lookup
  get  '/cart/quote/:recipient', to: 'store#quote', as: :send_quote
  get  '/cart/delete',  to: 'store#delete_cart', as: :delete_cart
  post '/cart/activate_code', to: 'store#activate_code', as: :activate_code
  post '/correspondence/mail_form', to: 'correspondence#mail_form', as: :mail_form

  # Routes for the checkout process:
  #
  # 1) set order type
  post '/checkout/:order_id/order_type', to: 'checkout#order_type', as: :order_type
  # 2) enter checkout process
  get  '/checkout/:order_id', to: 'checkout#checkout',  as: :checkout
  # 3) select a shipping method
  get  '/checkout/:order_id/shipping_method/:method_id', to: 'checkout#shipping_method', as: :shipping_method
  # 4) create a shipment
  post '/checkout/:order_id/ship', to: 'checkout#ship', as: :ship
  # 5) get payment methods
  get  '/checkout/:order_id/payment_methods', to: 'checkout#payment_methods', as: :payment_methods
  # 6) enter payment information
  get  '/checkout/:order_id/pay/:method', to: 'checkout#pay', as: :pay
  # 7) verify credit card payment or return from online payment
  post '/checkout/:order_id/verify', to: 'checkout#verify', as: :verify
  get  '/checkout/:order_id/return', to: 'checkout#return', as: :return
  # 7b) handle online payment notify if the user failed to return herself
  get  '/checkout/:order_id/notify', to: 'checkout#notify', as: :notify
  # 7c) confirm order when payment is not collected
  post '/checkout/:order_id/confirm', to: 'checkout#confirm', as: :confirm
  # 8) show a receipt
  get  '/checkout/:order_id/receipt', to: 'checkout#receipt', as: :receipt

  # Product specific routes.
  post '/product/:product_id/order', to: 'store#order_product', as: :order_product
  post '/product/:product_id/set_order_amount', to: 'store#set_order_amount', as: :set_order_amount

  # Favorite manipulation.
  get    '/store/favorites', to: 'store#show_favorites', as: :favorites
  get    '/store/favorites/:product_id', to: 'store#show_favorite', as: :show_favorite
  post   '/store/favorites/:product_id', to: 'store#add_favorite', as: :add_favorite
  delete '/store/favorites/:product_id', to: 'store#remove_favorite', as: :remove_favorite

  # Category, tag, department, promotion, and product views.
  get '/category/:category_id', to: 'store#show_category', as: :show_category
  get '/category/:category_id/order', to: 'store#show_category_order', as: :show_category_order
  get '/tag/:tag_id', to: 'store#show_tag', as: :show_tag
  get '/department/:department_id', to: 'store#show_department', as: :show_department
  get '/promotion/:promotion_id', to: 'store#show_promotion', as: :show_promotion
  get '/product/:product_id(/:category_id)', to: 'store#show_product', as: :show_product
  get '/products/promoted', to: 'store#show_promoted_products', as: :show_promoted_products

  # These routes can be reached via /:slug
  get '/front', to: 'store#front', as: :front
  get '/cart',  to: 'store#cart',  as: :cart

  # Content consumer actions.
  get '/content/feed', to: 'content#feed', as: :content_feed

  # Koala actions
  get 'koala/feed'

  # If we get here, the url is seen as a slug of a page. If the page
  # is internal, its slug will match one of the above routes.
  get '/:slug', to: 'store#show_page', as: :show_page, slug: /[a-z0-9_-]+/

  namespace :admin do
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    get '/reports', to: 'reports#index', as: :reports
    get '/reports/inventory', to: 'reports#inventory', as: :inventory_report
    get '/reports/sales', to: 'reports#sales', as: :sales_report
    get '/reports/sales_tax', to: 'reports#sales_tax', as: :sales_tax_report
    get '/reports/purchases', to: 'reports#purchases', as: :purchases_report
    get '/reports/product/:product_id/sales', to: 'reports#product_sales', as: :product_sales

    resources :stores do
      resources :hostnames, shallow: true
      resources :pictures, shallow: true
      resource :style
    end
    resources :subscriptions
    resources :groups do
      resources :users, only: [:index, :new, :create] do
        patch :join, on: :member
      end
      member do
        patch :make_default
        get :select_categories
        patch :toggle_category
      end
      post :reorder, on: :collection
    end
    resources :users, except: [:index, :new, :create] do
      resources :roles, only: [] do
        patch :toggle, on: :member
      end
    end
    resources :policies do
      patch :accept, on: :member
    end
    resources :tax_categories do
      post :reorder, on: :collection
    end
    resources :inventories do
      post :reorder, on: :collection
    end
    resources :inventory_items do
      resources :inventory_entries, shallow: true, only: :create
      collection do
        get :query
        get :refresh
      end
    end
    resources :inventory_checks do
      resources :inventory_check_items, shallow: true do
        member do
          patch :approve
          patch :discard
        end
      end
      member do
        patch :complete
        get :resolve
        patch :conclude
      end
    end
    resources :properties do
      post :reorder, on: :collection
    end
    resources :tags do
      resources :pictures, shallow: true
    end
    resources :transfers do
      resources :transfer_items, shallow: true
      patch :complete, on: :member
    end
    resources :activities, only: [:index, :show] do
      get :context, on: :collection
    end
    resources :departments do
      resources :pictures, shallow: true
      post :reorder, on: :collection
    end
    resources :categories do
      resources :pictures, shallow: true
      post :rearrange, on: :collection
      get :reorder_products, on: :member
    end
    resources :pages do
      resources :pictures, shallow: true
      resources :sections, shallow: true do
        resources :pictures
        resources :columns do
          resources :pictures
          resources :segments do
            resources :pictures
            resources :documents
            member do
              get :settings
              patch :modify
              get :copy
            end
            collection do
              post :reorder
              post :paste
            end
          end
          member do
            get :settings
            patch :modify
          end
        end
        member do
          get :preload
          get :settings
          patch :modify
        end
        post :reorder, on: :collection
      end
      member do
        get :layout
        post :duplicate
      end
      post :rearrange, on: :collection
    end
    resources :images do
      get :select, on: :member
    end
    resources :products do
      resources :pictures, shallow: true
      resources :documents, shallow: true
      resources :product_properties, shallow: true
      resources :alternate_prices
      resources :inventory_items, shallow: true
      resources :component_entries, shallow: true do
        post :reorder, on: :collection
      end
      resources :requisite_entries, shallow: true do
        post :reorder, on: :collection
      end
      collection do
        get :query
        get 'pricing(/:group_id)', action: :pricing, as: :pricing
        post :reorder
        post :upload_file
      end
      member do
        post :add_requisite_entries
        post :duplicate
        patch 'set_price(/:group_id)', action: :set_price, as: :set_price
        patch :make_primary
      end
    end
    resources :promotions do
      resources :promoted_items, shallow: true
      resources :pictures, shallow: true
      post :add_products, on: :member
      post :add_categories, on: :member
    end
    resources :order_types
    resources :shipping_methods do
      resources :pictures, shallow: true
    end
    resources :orders do
      resources :pictures, shallow: true
      resources :order_items, shallow: true, except: [:index]
      resources :shipments, shallow: true do
        member do
          patch :refresh
          patch :complete
          get :label
        end
      end
      collection do
        get :incoming
        get :outgoing
      end
      member do
        get :forward
        get :preview
        patch :approve
        get :review
        patch :conclude
      end
    end
    resources :order_items, only: [:index]

    post '/hostnames/reorder', to: 'hostnames#reorder', as: :reorder_hostnames
    post '/pictures/reorder', to: 'pictures#reorder', as: :reorder_pictures
    post '/documents/reorder', to: 'documents#reorder', as: :reorder_documents
    post '/pictures/delete', to: 'pictures#delete', as: :delete_picture
    post '/documents/delete', to: 'documents#delete', as: :delete_document
  end

  if Rails.env.production?

app/controllers/admin/order_items_controller.rb
class Admin::OrderItemsController < AdminController

  before_action :set_order_and_item, except: [:index, :create]

  # GET /admin/order_items
  def index
    authorize_action_for OrderItem, at: current_store

    order_types = current_group.incoming_order_types
    query = saved_search_query('order_item', 'admin_order_item_search')
    query.merge!('order_type' => order_types)
    @search = OrderItemSearch.new(query.merge(search_constrains))
    results = @search.results.pending
    @order_items = results.page(params[:page])
    @customers = UserSearch.new(
      store: current_store,
      group: order_types.map(&:source),
      except_group: current_store.default_group
    ).results
    @products = current_store.products
      .find((query['product_id'] || []).reject(&:blank?))
  end

  # POST /admin/orders/1/order_items.js
  # Use Order#insert to create order items correctly.
  def create
    authorize_action_for OrderItem, at: current_store
    @order = current_store.orders.find(params[:order_id])
    @product = if order_item_params[:customer_code].present?
      current_store.products.live.find_by(customer_code: order_item_params[:customer_code])
    else
      current_store.products.live.find_by(id: order_item_params[:product_id])
    end
    amount = order_item_params[:amount].to_i
    options = {lot_code: lot_code_or_serial}

    respond_to do |format|
      if @order_item = @order.insert(@product, amount, @order.source, options)
        track @order_item, @order
        @order.recalculate!
        format.js { render :create }
      else
        format.js { render :error }
      end
    end
  end

  # PATCH/PUT /admin/order_items/1.js
  def update
    authorize_action_for @order_item, at: current_store

    if @order_item.update(order_item_params)
      track @order_item, @order
      @order.recalculate!
    end

    respond_to :js
  end

  # DELETE /admin/order_items/1.js
  def destroy
    authorize_action_for @order_item, at: current_store

    if @order_item.destroy
      track @order_item, @order
      @order.recalculate!
    end

    respond_to :js
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_and_item
      @order_item = OrderItem.find(params[:id])
      @order = @order_item.order
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(
        :product_id, :amount, :lot_code, :serial,
        :price, :customer_code
      )
    end

    def search_constrains
      {store: current_store, all_time: true}
    end

    # Use lot code if found, serial otherwise.
    def lot_code_or_serial
      order_item_params[:lot_code].presence || order_item_params[:serial].presence
    end
end

app/controllers/order_items_controller.rb
#
# This controller deals with editing and deleting items in the shopping cart.
#
class OrderItemsController < BaseStoreController

  # This controller is aware of unauthenticated guests.
  def current_user
    super || guest_user
  end

  # Guest users may edit their shopping cart contents.
  before_action :authenticate_user_or_skip!
  before_action :set_order_and_item

  # PATCH/PUT /order_items/1
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        if @order_item.amount < 1
          @order_item.destroy
          format.js { render :destroy }
        else
          @order_item.reset_subitems!
          @order.recalculate!
          format.js { render :update }
        end
      else
        format.js { render :rollback }
      end
    end
  end

  # DELETE /order_items/1
  def destroy
    if @order_item.destroy
      @order.recalculate!
    end
  end

  private
    def set_order_and_item
      @order = shopping_cart
      @order_types = @order.available_order_types
      @order_item = @order.order_items.find(params[:id])
    end

    def order_item_params
      params.require(:order_item).permit(
        :amount
      )
    end
end

app/controllers/pos/order_items_controller.rb
#
# This is the point-of-sale specific controller for order items.
#
class Pos::OrderItemsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_order_types

  layout 'point_of_sale'

  # POST /pos/orders/1/order_items
  # Use Order#insert to create order items correctly.
  def create
    @product = current_store.products.live.find_by(id: order_item_params[:product_id])
    amount = order_item_params[:amount].to_i
    options = {lot_code: order_item_params[:lot_code]}
    respond_to do |format|
      if @order_item = @order.insert(@product, amount, @order.source, options)
        @order.recalculate!
        format.js { render :create }
      else
        format.js { render :error }
      end
    end
  end

  # PATCH/PUT /pos/order_items/1
  def update
    @order_item = @order.order_items.find(params[:id])

    respond_to do |format|
      if @order_item.update(order_item_params)
        if @order_item.amount < 1
          @order_item.destroy
          format.js { render :destroy }
        else
          @order_item.reset_subitems!
          @order.recalculate!
          format.js { render :update }
        end
      else
        format.js { render :rollback }
      end
    end
  end

  # DELETE /pos/order_items/1
  def destroy
    @order_item = OrderItem.find(params[:id])
    @order = @order_item.order

    if @order_item.destroy
      @order.recalculate!
    end
  end

  private
    def set_order_types
      @order = shopping_cart
      @order_types = @order.available_order_types
    end

    def order_item_params
      params.require(:order_item).permit(
        :product_id, :amount, :lot_code
      )
    end
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/pos/order_items_helper.rb
module Pos::OrderItemsHelper
end

app/views/admin/order_items/_edit_row.html.haml
%tr[order_item]
  %td.visible-print
    %span.badge= order_item_counter + 1
  %td
    - if order_item.lot_code.present?
      .pull-right
        .label.label-primary= order_item.lot_code
    = product_header order_item
    - if order_item.additional_info.present?
      .additional-info
        = order_item.product.additional_info_prompt
        %strong= order_item.additional_info
    - if order_item.product.shipping_notes.present?
      .small
        = icon('info-circle')
        = order_item.product.shipping_notes
  - if current_user.can_update?(order_item, at: current_store)
    %td.control
      = form_for [:admin, order_item], remote: true,
          html: {class: 'pull-right immediate'} do |f|
        = f.number_field :amount, min: 1, class: 'form-control text-right', tabindex: 1
  - else
    %td.text-right
      = order_item.amount
  %td.text-right.currency
    = money order_item.includes_tax? ? order_item.price_with_tax : order_item.price_sans_tax
  %td.text-right.currency
    = money order_item.includes_tax? ? order_item.subtotal_with_tax : order_item.subtotal_sans_tax
  %td.actions
    - if current_user.can_delete?(order_item, at: current_store)
      = link_to icon('remove'), admin_order_item_path(order_item), remote: true, method: :delete, class: 'btn btn-outline-danger btn-sm'

- if order_item.adjustments.any?
  = render partial: 'adjustments/row', collection: order_item.adjustments, as: :adjustment, locals: {includes_tax: order_item.includes_tax?}

app/views/admin/order_items/_edit_table.html.haml
#order-items-table
  %table.table.table-form.table-hover
    %caption.text-right
      %em.small= order.includes_tax? ? t('orders.receipt.tax_included') : t('orders.receipt.tax_excluded')
    %thead
      %tr
        %th.col-min.visible-print
        %th= col(OrderItem, :product_title)
        %th.col-xs-1.text-right= col(OrderItem, :amount)
        %th.col-xs-2.text-right= col(OrderItem, :price)
        %th.col-xs-2.text-right= col(OrderItem, :subtotal)
        %th.col-min.actions
    %tfoot
      %tr
        %th.visible-print
        %th
        %th.text-right{colspan: 2}= col(Order, :grand_total)
        %th.text-right.currency
          = render partial: 'admin/orders/grand_total', object: order, as: :order
        %th.actions
    %tbody
      = render partial: 'admin/order_items/edit_row', collection: order.order_items, as: :order_item
      - if order.adjustments.any?
        = render partial: 'adjustments/row', collection: order.adjustments, as: :adjustment, locals: {includes_tax: order.includes_tax?}

app/views/admin/order_items/_new.html.haml
#admin-order-item-form{data: {'product-query-url': query_admin_products_path, inventory: order.inventory.present? && order.inventory.id}}
  = bootstrap_form_for [:admin, order, OrderItem.new(amount: 1)], remote: true do |f|
    %fieldset
      .row
        .col-xs-12.col-sm-12.col-md-6
          = f.select :product_id, [], {skip_label: true}, {placeholder: t('.product_query'), class: 'selectize-tall selectize-list-group'}
        .col-xs-6.col-sm-6.col-md-4
          = f.text_field :lot_code, skip_label: true, disabled: true, placeholder: col(OrderItem, :lot_code)
        .col-xs-6.col-sm-6.col-md-2
          .form-group
            .input-group
              = f.number_field_without_bootstrap :amount, min: 1, placeholder: col(OrderItem, :amount), class: 'form-control text-right'
              .input-group-btn
                = f.button class: 'btn btn-success' do
                  = t('.submit')

  :coffee
    $('#order_item_product_id').betterSelectize
      valueField: 'id'
      sortField: [{field: 'title'}, {field: 'subtitle'}]
      searchField: ['code', 'customer_code', 'title', 'subtitle']
      diacritics: false
      render: $.fn.selectize.product_renderer
      load: (query, callback) ->
        return callback() unless query.length > 2
        $.ajax
          url: $('#admin-order-item-form').data 'productQueryUrl'
          type: 'GET'
          dataType: 'json'
          data:
            q: query
            purposes: ['vanilla', 'bundle', 'composite', 'package']
            having_variants: false
          error: ->
            callback()
          success: (response) ->
            callback(response)
      onChange: (id) ->
        $lot_code = $('#order_item_lot_code')[0].selectize
        inventory = $('#admin-order-item-form').data 'inventory'
        if id and inventory?
          $lot_code.setValue null
          $lot_code.clearOptions()
          $lot_code.load (callback) ->
            $.ajax
              url: $('#order_item_product_id')[0].selectize.options[id].url
              type: 'GET'
              dataType: 'json'
              error: ->
                callback()
              success: (response) ->
                $lot_code.enable()
                callback(response.inventory[inventory])

    $('#order_item_lot_code').betterSelectize
      valueField: 'code'
      searchField: 'code'
      maxItems: 1
      render: $.fn.selectize.inventory_renderer

app/views/admin/order_items/_order_item.html.haml
= content_tag_for :tr, order_item do
  - if order_item.order.approval
    %td= order_item.product_code
    %td
      %strong= order_item.product_title
      = order_item.product_subtitle
  - else
    %td= order_item.product.code
    %td
      %strong= order_item.product.title
      = order_item.product.subtitle
  %td.text-right= order_item.amount

app/views/admin/order_items/_pending.html.haml
#pending-items-table
  - unless order.fully_shipped?
    .table-responsive
      %table.table.table-hover
        %caption= icon('exclamation-circle', t('.title'))
        %thead
          %tr
            %th= col(OrderItem, :product_title)
            %th.col-xs-2= col(OrderItem, :lot_code)
            %th.col-xs-1.text-right= col(OrderItem, :ordered)
            %th.col-xs-1.text-right= col(OrderItem, :shipped)
        %tbody
          - order.order_items.pending.each do |order_item|
            %tr
              %td= product_header order_item
              %td= order_item.lot_code
              %td.text-right= order_item.amount
              %td.text-right.warning.text-warning
                = order_item.shipped || 0

app/views/admin/order_items/_row.html.haml
%tr[order_item]{class: order_item.is_subitem? && 'subrow'}
  %td.visible-print
    %span.badge= order_item_counter + 1
  %td
    - if order_item.lot_code.present?
      .pull-right
        .label.label-primary= order_item.lot_code
    = product_header order_item
    - if order_item.additional_info.present?
      .additional-info
        = order_item.product.additional_info_prompt
        %strong= order_item.additional_info
    - if order_item.product.shipping_notes.present?
      .small
        = icon('info-circle')
        = order_item.product.shipping_notes
  %td.text-right= order_item.amount
  %td.text-right{class: order_item.pending? && 'warning text-warning'}
    - if order_item.tangible?
      = order_item.shipped || 0
  %td.text-right.currency.zero-width-print
    .hidden-print
      = money order_item.includes_tax? ? order_item.subtotal_with_tax : order_item.subtotal_sans_tax
  %td.actions

- if order_item.adjustments.any?
  .hidden-print
    = render partial: 'adjustments/row', collection: order_item.adjustments, as: :adjustment, locals: {includes_tax: order_item.includes_tax?}

app/views/admin/order_items/_search.html.haml
.panel.panel-info
  .panel-heading
    %h4.panel-title= t('actions.search')
  .panel-body
    = form_for @search, url: admin_order_items_path, method: :get do |f|
      .row
        .col-sm-12.col-md-12
          .form-group
            = f.select :product_id, [], {}, {multiple: true, placeholder: t('.product_query'), class: 'selectize-tall selectize-list-group', data: {products: @products, selected: @search.raw_options['product_id']}}
        .col-sm-8.col-md-10
          .form-group
            = f.select :customer_id, @customers.map { |c| [c.to_s, c.id] }, {include_blank: t('.customer')}, {class: 'form-control selectize'}
        .col-sm-4.col-md-2
          .form-group
            = f.submit t('actions.search'), class: 'btn btn-block btn-primary'

:coffee
  $product = $('#order_item_search_product_id')
  products = $product.data 'products'
  selected = $product.data 'selected'

  $product.betterSelectize
    options: products
    items: selected
    valueField: 'id'
    sortField: [{field: 'title'}, {field: 'subtitle'}]
    searchField: ['code', 'customer_code', 'title', 'subtitle']
    diacritics: false
    render: $.fn.selectize.product_renderer
    load: (query, callback) ->
      return callback() unless query.length > 2
      $.ajax
        url: '#{query_admin_products_path}'
        type: 'GET'
        dataType: 'json'
        data:
          q: query
          having_variants: false
        error: ->
          callback()
        success: (response) ->
          callback(response)

app/views/admin/order_items/_table.html.haml
#order-items-table
  %table.table.table-hover
    %caption.hidden-print.text-right
      %em.small= order.includes_tax? ? t('orders.receipt.tax_included') : t('orders.receipt.tax_excluded')
    %thead
      %tr
        %th.col-min.visible-print
        %th= col(OrderItem, :product_title)
        %th.col-xs-1.text-right= col(OrderItem, :ordered)
        %th.col-xs-1.text-right
          - if order.track_shipments?
            = col(OrderItem, :shipped)
        %th.col-xs-2.text-right.zero-width-print
          .hidden-print= col(OrderItem, :subtotal)
        %th.actions
    %tfoot.hidden-print
      %tr
        %th.visible-print
        %th
        %th.text-right{colspan: 2}= col(Order, :grand_total)
        %th.text-right.currency
          = render partial: 'admin/orders/grand_total', object: order, as: :order
        %th.actions
    %tbody
      = render partial: 'admin/order_items/row', collection: order.order_items, as: :order_item

app/views/admin/order_items/create.js.haml
$('#order-items-table').replaceWith("#{j render partial: 'admin/order_items/edit_table', object: @order, as: :order}");
$('#admin-order-item-form').replaceWith("#{j render partial: 'admin/order_items/new', object: @order, as: :order}");
$("##{dom_id(@order_item)}").effect('highlight');

app/views/admin/order_items/destroy.js.haml
$('#order-items-table').replaceWith("#{j render partial: 'admin/order_items/edit_table', object: @order, as: :order}");

app/views/admin/order_items/index.html.haml
.page-header
  = link_to incoming_admin_orders_path, class: 'btn btn-default' do
    = icon('chevron-circle-left', t('actions.back'))
  %h1= icon('list', t('.title'))

= render partial: 'search'

%table.table.table-hover
  %thead
    %tr
      %th= col(OrderItem, :order_number)
      %th= col(OrderItem, :product_title)
      %th.col-xs-1.text-right= col(OrderItem, :ordered)
      %th.col-xs-1.text-right= col(OrderItem, :shipped)
      %th.actions
  %tbody
    - @order_items.each do |order_item|
      %tr[order_item]{class: order_item.is_subitem? && 'subrow'}
        %td= order_item.order.number
        %td
          - if order_item.lot_code.present?
            .pull-right
              .label.label-primary= order_item.lot_code
          = product_header order_item
          - if order_item.additional_info.present?
            .additional-info
              = order_item.product.additional_info_prompt
              %strong= order_item.additional_info
          - if order_item.product.shipping_notes.present?
            .small
              = icon('info-circle')
              = order_item.product.shipping_notes
        %td.text-right= order_item.amount
        %td.text-right= order_item.shipped
        %td.actions
          = link_to icon('info', t('actions.show')), admin_order_path(order_item.order), class: 'btn btn-default btn-sm'

= paginate @order_items

app/views/admin/order_items/update.js.haml
$('#order-items-table').replaceWith("#{j render partial: 'admin/order_items/edit_table', object: @order, as: :order}");
- if @order_item.valid?
  $("##{dom_id(@order_item)}").effect('highlight');