config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints(host: ENV['STELLAR_HOST']) do
    resource :onboarding do
      get :frontend
      get :backend
      get :admin
      post 'validate/:step', action: :validate, as: :validate
    end
    get '/', to: 'account#index'
    get '/get-started', to: 'account#onboarding', as: :get_started
  end

  root 'store#index'

  # Catch error conditions early.
  match '(errors)/:status', to: 'errors#show',
    constraints: {status: /\d{3}/},
    defaults: {status: '500'},
    via: :all

  # Point-of-sale interface.
  #namespace :pos do
  #  root 'main#index'
  #  resources :orders do
  #    resources :order_items, shallow: true
  #  end
  #  resources :products do
  #    get :query, on: :collection
  #  end
  #end

  # Mount stripe engine at /stripe
  mount Stripe::Engine => '/stripe'

  resources :orders do
    resources :order_items, shallow: true
    member do
      get :select
      get :preview
      patch :claim
      get :duplicate
    end
  end
  resource :profile, only: [:show, :edit, :update]

  # Catch bona fide storefront urls that are not accessible via slugs.
  get  '/store', to: 'store#index', as: :store
  get  '/store/lookup', to: 'store#lookup', as: :lookup
  get  '/cart/quote/:recipient', to: 'store#quote', as: :send_quote
  get  '/cart/delete',  to: 'store#delete_cart', as: :delete_cart
  post '/cart/activate_code', to: 'store#activate_code', as: :activate_code
  post '/correspondence/mail_form', to: 'correspondence#mail_form', as: :mail_form

  # Routes for the checkout process:
  #
  # 1) set order type
  post '/checkout/:order_id/order_type', to: 'checkout#order_type', as: :order_type
  # 2) enter checkout process
  get  '/checkout/:order_id', to: 'checkout#checkout',  as: :checkout
  # 3) select a shipping method
  get  '/checkout/:order_id/shipping_method/:method_id', to: 'checkout#shipping_method', as: :shipping_method
  # 4) create a shipment
  post '/checkout/:order_id/ship', to: 'checkout#ship', as: :ship
  # 5) get payment methods
  get  '/checkout/:order_id/payment_methods', to: 'checkout#payment_methods', as: :payment_methods
  # 6) enter payment information
  get  '/checkout/:order_id/pay/:method', to: 'checkout#pay', as: :pay
  # 7) verify credit card payment or return from online payment
  post '/checkout/:order_id/verify', to: 'checkout#verify', as: :verify
  get  '/checkout/:order_id/return', to: 'checkout#return', as: :return
  # 7b) handle online payment notify if the user failed to return herself
  get  '/checkout/:order_id/notify', to: 'checkout#notify', as: :notify
  # 7c) confirm order when payment is not collected
  post '/checkout/:order_id/confirm', to: 'checkout#confirm', as: :confirm
  # 8) show a receipt
  get  '/checkout/:order_id/receipt', to: 'checkout#receipt', as: :receipt

  # Product specific routes.
  post '/product/:product_id/order', to: 'store#order_product', as: :order_product
  post '/product/:product_id/set_order_amount', to: 'store#set_order_amount', as: :set_order_amount

  # Favorite manipulation.
  get    '/store/favorites', to: 'store#show_favorites', as: :favorites
  get    '/store/favorites/:product_id', to: 'store#show_favorite', as: :show_favorite
  post   '/store/favorites/:product_id', to: 'store#add_favorite', as: :add_favorite
  delete '/store/favorites/:product_id', to: 'store#remove_favorite', as: :remove_favorite

  # Category, tag, department, promotion, and product views.
  get '/category/:category_id', to: 'store#show_category', as: :show_category
  get '/category/:category_id/order', to: 'store#show_category_order', as: :show_category_order
  get '/tag/:tag_id', to: 'store#show_tag', as: :show_tag
  get '/department/:department_id', to: 'store#show_department', as: :show_department
  get '/promotion/:promotion_id', to: 'store#show_promotion', as: :show_promotion
  get '/product/:product_id(/:category_id)', to: 'store#show_product', as: :show_product
  get '/products/promoted', to: 'store#show_promoted_products', as: :show_promoted_products

  # These routes can be reached via /:slug
  get '/front', to: 'store#front', as: :front
  get '/cart',  to: 'store#cart',  as: :cart

  # Content consumer actions.
  get '/content/feed', to: 'content#feed', as: :content_feed

  # Koala actions
  get 'koala/feed'

  # If we get here, the url is seen as a slug of a page. If the page
  # is internal, its slug will match one of the above routes.
  get '/:slug', to: 'store#show_page', as: :show_page, slug: /[a-z0-9_-]+/

  namespace :admin do
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    get '/reports', to: 'reports#index', as: :reports
    get '/reports/inventory', to: 'reports#inventory', as: :inventory_report
    get '/reports/sales', to: 'reports#sales', as: :sales_report
    get '/reports/sales_tax', to: 'reports#sales_tax', as: :sales_tax_report
    get '/reports/purchases', to: 'reports#purchases', as: :purchases_report
    get '/reports/product/:product_id/sales', to: 'reports#product_sales', as: :product_sales

    resources :stores do
      resources :hostnames, shallow: true
      resources :pictures, shallow: true
      resource :style
    end
    resources :subscriptions
    resources :groups do
      resources :users, only: [:index, :new, :create] do
        patch :join, on: :member
      end
      member do
        patch :make_default
        get :select_categories
        patch :toggle_category
      end
      post :reorder, on: :collection
    end
    resources :users, except: [:index, :new, :create] do
      resources :roles, only: [] do
        patch :toggle, on: :member
      end
    end
    resources :policies do
      patch :accept, on: :member
    end
    resources :tax_categories do
      post :reorder, on: :collection
    end
    resources :inventories do
      post :reorder, on: :collection
    end
    resources :inventory_items do
      resources :inventory_entries, shallow: true, only: :create
      collection do
        get :query
        get :refresh
      end
    end
    resources :inventory_checks do
      resources :inventory_check_items, shallow: true do
        member do
          patch :approve
          patch :discard
        end
      end
      member do
        patch :complete
        get :resolve
        patch :conclude
      end
    end
    resources :properties do
      post :reorder, on: :collection
    end
    resources :tags do
      resources :pictures, shallow: true
    end
    resources :transfers do
      resources :transfer_items, shallow: true
      patch :complete, on: :member
    end
    resources :activities, only: [:index, :show] do
      get :context, on: :collection
    end
    resources :departments do
      resources :pictures, shallow: true
      post :reorder, on: :collection
    end
    resources :categories do
      resources :pictures, shallow: true
      post :rearrange, on: :collection
      get :reorder_products, on: :member
    end
    resources :pages do
      resources :pictures, shallow: true
      resources :sections, shallow: true do
        resources :pictures
        resources :columns do
          resources :pictures
          resources :segments do
            resources :pictures
            resources :documents
            member do
              get :settings
              patch :modify
              get :copy
            end
            collection do
              post :reorder
              post :paste
            end
          end
          member do
            get :settings
            patch :modify
          end
        end
        member do
          get :preload
          get :settings
          patch :modify
        end
        post :reorder, on: :collection
      end
      member do
        get :layout
        post :duplicate
      end
      post :rearrange, on: :collection
    end
    resources :images do
      get :select, on: :member
    end
    resources :products do
      resources :pictures, shallow: true
      resources :documents, shallow: true
      resources :product_properties, shallow: true
      resources :alternate_prices
      resources :inventory_items, shallow: true
      resources :component_entries, shallow: true do
        post :reorder, on: :collection
      end
      resources :requisite_entries, shallow: true do
        post :reorder, on: :collection
      end
      collection do
        get :query
        get 'pricing(/:group_id)', action: :pricing, as: :pricing
        post :reorder
        post :upload_file
      end
      member do
        post :add_requisite_entries
        post :duplicate
        patch 'set_price(/:group_id)', action: :set_price, as: :set_price
        patch :make_primary
      end
    end
    resources :promotions do
      resources :promoted_items, shallow: true
      resources :pictures, shallow: true
      post :add_products, on: :member
      post :add_categories, on: :member
    end
    resources :order_types
    resources :shipping_methods do
      resources :pictures, shallow: true
    end
    resources :orders do
      resources :pictures, shallow: true
      resources :order_items, shallow: true, except: [:index]
      resources :shipments, shallow: true do
        member do
          patch :refresh
          patch :complete
          get :label
        end
      end
      collection do
        get :incoming
        get :outgoing
      end
      member do
        get :forward
        get :preview
        patch :approve
        get :review
        patch :conclude
      end
    end
    resources :order_items, only: [:index]

    post '/hostnames/reorder', to: 'hostnames#reorder', as: :reorder_hostnames
    post '/pictures/reorder', to: 'pictures#reorder', as: :reorder_pictures
    post '/documents/reorder', to: 'documents#reorder', as: :reorder_documents
    post '/pictures/delete', to: 'pictures#delete', as: :delete_picture
    post '/documents/delete', to: 'documents#delete', as: :delete_document
  end

  if Rails.env.production?

app/controllers/orders_controller.rb
class OrdersController < BaseStoreController

  # This controller is aware of unauthenticated guests.
  def current_user
    super || guest_user
  end

  # Unauthenticated guests may browse their orders.
  before_action :authenticate_user_or_skip!
  before_action :set_categories, only: [:index, :show, :edit]
  before_action :set_order, only: [:show, :edit, :update, :destroy, :duplicate]

  authority_actions duplicate: 'read', select: 'read', preview: 'read', claim: 'update'

  # GET /orders
  def index
    query = saved_search_query('order', 'order_search')
    @search = OrderSearch.new(query.merge(search_constrains))
    results = @search.results.complete
    @orders = results.page(params[:page])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    authorize_action_for @order, at: current_store
    track @order

    respond_to :js, :json, :html
  end

  # GET /orders/new
  def new
    authorize_action_for Order, at: current_store

    @groups = all_groups
    @group = find_selected_group || @groups.first
    @customers = customer_selection
    @customer = find_selected_customer || User.new(
      shipping_country: Country.default,
      billing_country: Country.default
    )
    @order = current_store.orders.build(
      group_id: @group.id,
      customer: @customer,
      order_type: @group.outgoing_order_types.first
    )
    @order.customer = @customer

    respond_to :html, :js
  end

  # GET /orders/1/edit
  def edit
    authorize_action_for @order, at: current_store
    track @order
  end

  # POST /orders
  def create
    authorize_action_for Order, at: current_store

    @groups = all_groups
    @group = find_selected_group
    @customers = customer_selection
    @order = current_store.orders.build(order_params.merge(user: current_user))
    @order.address_to_customer
    @order.includes_tax = @group.price_tax_included?
    new_customer = @order.customer.new_record?

    respond_to do |format|
      if @order.save
        track @order
        @order.customer.groups << @group if new_customer
        user_session['shopping_cart_id'] = @order.id

        format.html { redirect_to cart_path, notice: t('.notice', order: @order) }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /orders/1
  # The checkout process calls this via AJAX any time the order status changes.
  # Completes an order if it's ready for completion. Orders targeted at another
  # customer are approved at completion. Responses are in JSON.
  # Returns an error if the order itself does not validate, or it has become
  # uncheckoutable until completed.
  # HTML responses are sent when the user edits her own completed orders.
  def update
    authorize_action_for @order, at: current_store

    respond_to do |format|
      if @order.update(order_params) && (@order.checkoutable? || @order.complete?)
        if @order.should_complete?
          @order.complete!
          @order.update(approved_at: Date.current) if @order.targeted?
        end

        format.json { render json: @order }
        format.html { redirect_to order_path(@order), notice: t('.notice', order: @order) }
      else
        format.json { render json: @order.errors, status: :unprocessable_entity }
        format.html { render :edit }
      end
    end
  end

  # DELETE /orders/1
  def destroy
    authorize_action_for @order, at: current_store
    track @order

    @order.update(cancelled_at: Time.current)
    @order.email(:cancellation, @order.customer_string)

    respond_to do |format|
      format.html { redirect_to orders_path,
        notice: t('.notice', order: @order) }
    end
  end

  # GET /orders/1/duplicate
  def duplicate
    authorize_action_for @order, at: current_store

    @order.copy_items_to(shopping_cart)
    shopping_cart.recalculate!

    redirect_to cart_path, notice: t('.notice', order: @order)
  end

  # GET /orders/1/select
  # Users with customer selection role may use this action to select
  # a different order as the current shopping cart. If the selection
  # matches the default shopping cart, it is cleared instead.
  def select
    @order = current_store.orders.find(params[:id])
    authorize_action_for @order, at: current_store

    if can_select_customer?
      if @order.targeted?
        user_session['shopping_cart_id'] = @order.id
      else
        user_session.delete('shopping_cart_id')
      end
      redirect_to cart_path
    else
      head :forbidden
    end
  end

  # GET /orders/1/preview
  # Users with customer selection role may preview quotes (orders)
  # and claim them as their own to continue working on them.
  def preview
    @order = current_group.user_orders.at(current_store).find(params[:id])
    authorize_action_for Order, at: current_store
  end

  # PATCH/PUT /orders/1/claim
  def claim
    authorize_action_for Order, at: current_store
    @order = current_group.user_orders.at(current_store).find(params[:id])
    if can_select_customer?
      previous_owner = @order.user
      @order.update(user: current_user)
      user_session['shopping_cart_id'] = @order.id
      redirect_to cart_path, notice: t('.notice', from: previous_owner)
    else
      head :forbidden
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = current_user.orders.find(params[:id])
    end

    # All groups except the default are available for selection.
    def all_groups
      current_store.groups.not_including(current_store.default_group)
    end

    def find_selected_group
      order_params[:group_id].present? &&
        current_store.groups.find_by(id: order_params[:group_id])
    end

    def find_selected_customer
      order_params[:customer_id].present? &&
        current_store.users.find_by(id: order_params[:customer_id])
    end

    # Customers can be selected from the selected group only.
    def customer_selection
      UserSearch.new(
        store: current_store,
        group: @group
      ).results
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {}).permit(
        :group_id, :order_type_id, :customer_id, :inventory_id,
        :completed_at, :shipping_at, :installation_at,
        :vat_number, :your_reference, :our_reference, :message,
        :customer_name, :customer_email, :customer_phone,
        :company_name, :contact_person, :contact_email, :contact_phone,
        :has_billing_address,
        :billing_address, :billing_postalcode,
        :billing_city, :billing_country_code,
        :shipping_address, :shipping_postalcode,
        :shipping_city, :shipping_country_code,
        :notes,
        customer_attributes: [
          :id, :initial_group_id, :email, :name, :phone,
          :shipping_address, :shipping_postalcode,
          :shipping_city, :shipping_country_code,
          :billing_address, :billing_postalcode,
          :billing_city, :billing_country_code
        ]
      )
    end

    # The search is limited to the current user's personal history.
    def search_constrains
      {store: current_store, user_id: current_user.id}
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper

  def back_path_for(order)
    order_type = order.order_type
    return incoming_admin_orders_path if current_group.incoming_order_types.include?(order_type)
    return outgoing_admin_orders_path if current_group.outgoing_order_types.include?(order_type)
    admin_orders_path
  end
end

app/helpers/pos/orders_helper.rb
module Pos::OrdersHelper
end

app/views/admin/orders/_edit.html.haml
.navbar-panel
  .container
    %fieldset#barcode-panel{data: {url: admin_order_order_items_path(order)}}
      .form-group
        .input-group
          = text_field_tag 'barcode', nil, autocomplete: 'off', class: 'form-control monospace', placeholder: t('.barcode')
          .input-group-btn
            %button.btn.btn-default{type: 'button', data: {toggle: 'collapse', target: '.navbar-panel .collapse'}}
              = t('.add_order_items')
              %span.caret
    .collapse
      .navbar-panel-extension
        = render partial: 'admin/order_items/new', object: order, as: :order

:coffee
  fields =
    '01': 'customer_code'
    '10': 'lot_code'
    '21': 'serial'
    '30': 'amount'

  new Switchboard 'barcode',
    mapping:
      'Dead': String.fromCharCode(29) #dead key to FNC1
      '¨': String.fromCharCode(29)
    callback: (code) ->
      data = parseBarcode code
      item = {amount: 1}
      for i in data.parsedCodeItems
        item[fields[i.ai]] = i.data if fields[i.ai]?
      $('#barcode').val ''
      $.ajax
        url: $('#barcode-panel').data 'url'
        type: 'POST'
        data:
          order_item: item

app/views/admin/orders/_form_for_new.html.haml
= bootstrap_form_for [:admin, order] do |f|
  .col-lg-5
    .panel.panel-primary
      .panel-heading
        %h4.panel-title= t('.order_meta')
      .panel-body
        %fieldset
          = f.select :group_id, @groups.map { |g| [g.name, g.id, data: {appearance: g.appearance}.to_json] }, label: t('.group_id')
          = f.select :customer_id, @customers.map { |c| [c.to_s, c.id] }, {include_blank: t('.new_customer')}
          %hr
          .row
            .col-md-6
              = f.select :order_type_id, @group.outgoing_order_types.map { |o| [o.to_s, o.id] }
            .col-md-6
              = f.select :inventory_id, @group.available_inventories.map { |i| [i.to_s, i.id] }
  .col-lg-6.col-lg-offset-1
    .panel.panel-default
      .panel-heading
        %h4.panel-title= t('.customer')
      .panel-body
        %fieldset
          = render partial: 'customer_fields', locals: {f: f}
          %fieldset.actions.fixed
            .container
              = f.primary

:coffee
  refresh = (customer_id) ->
    group_id = group_select.getValue()
    $.ajax
      url: '#{new_admin_order_path}'
      type: 'GET'
      dataType: 'script'
      data:
        order:
          group_id: group_id
          customer_id: customer_id

  $group_select = $('#order_group_id').betterSelectize
    labelField: 'title'
    dataAttr: 'data'
    render: $.fn.selectize.label_renderer
    onChange: (id) ->
      $.ajax
        url: '#{new_admin_order_path}'
        type: 'GET'
        dataType: 'script'
        data:
          order:
            group_id: id

  $customer_select = $('#order_customer_id').betterSelectize
    onFocus: ->
      this.clear true unless this.getValue()
    onBlur: ->
      id = this.getValue()
      refresh id unless id
    onChange: (id) ->
      if this.items.length
        refresh id

  $order_type_select = $('#order_order_type_id').betterSelectize
    valueField: 'id'
    labelField: 'name'

  $inventory_select = $('#order_inventory_id').betterSelectize
    valueField: 'id'
    labelField: 'name'

  group_select = $group_select[0].selectize
  customer_select = $customer_select[0].selectize
  order_type_select = $order_type_select[0].selectize
  inventory_select = $inventory_select[0].selectize

app/views/admin/orders/_headers.html.haml
- letterhead = @order.destination.letterhead
- if letterhead.present?
  = render partial: 'pages/content', object: letterhead, as: :page

.page-header
  %h1
    = t('.delivery_note')
    %span.small= @order.last_completed_shipment

app/views/admin/orders/_review_modal.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header.bg-primary
      %button.close{data: {dismiss: 'modal'}}= icon('close')
      %h4.modal-title= t('.title')
    .modal-body
      .small
        = render partial: 'summary'
    .modal-body
      %h5= t('.shipments')
      = render partial: 'shipments'
    .modal-body
      %h5= t('.contents')
      = render partial: 'contents', locals: {display_stock: false}
    .modal-footer
      = link_to icon('gavel', t('.conclude')), conclude_admin_order_path(@order), remote: true, method: :patch, data: {disable_with: button_spinner}, class: 'btn btn-primary'

app/views/admin/orders/_row.html.haml
%tr[order]{class: order.appearance}
  %td= icon(order.icon)
  %td
    %strong= order.number
  %td= order.completed_at.present? ? l(order.completed_at.to_date) : nil
  - if current_store.b2b_sales?
    %td
      = order.shipping_at.present? ? l(order.shipping_at) : nil
      \/
      = order.installation_at.present? ? l(order.installation_at) : nil
  %td
    %strong= order.customer_name
    - if current_store.b2b_sales?
      .small= order.summary
  %td.text-right= order.order_items_count
  %td.text-right.currency
    = money order.includes_tax? ? order.grand_total_with_tax : order.grand_total_sans_tax
  %td.actions
    - if current_user.can_update?(Order, at: current_store) && order.destination == current_group
      - if order.current?
        = link_to icon('search', t('.preview')), preview_admin_order_path(order), remote: true, class: 'btn btn-sm btn-outline-primary'
      - if order.concludable?
        = link_to icon('gavel', t('.review')), review_admin_order_path(order), remote: true, class: 'btn btn-sm btn-outline-primary'
    = link_to icon('info', t('actions.show')), admin_order_path(order),
        class: 'btn btn-default btn-sm'
    - if current_user.can_update?(Order, at: current_store)
      = link_to icon('edit', t('actions.edit')), edit_admin_order_path(order), class: 'btn btn-default btn-sm'
    - if current_user.can_delete?(Order, at: current_store) && order.incomplete?
      = link_to icon('remove', t('actions.delete')), admin_order_path(order), method: :delete, class: 'btn btn-sm btn-outline-danger', data: {confirm: t('actions.confirm.body', klass: Order.model_name.human, name: order.to_s), 'confirm-title': t('actions.confirm.title'), 'confirm-proceed': t('actions.confirm.proceed'), 'confirm-cancel': t('actions.confirm.cancel')}

app/views/admin/orders/_search.html.haml
.panel.panel-info
  .panel-heading
    %h4.panel-title= t('actions.search')
  .panel-body
    = form_for @search, url: url, method: :get do |f|
      .row
        .col-sm-6.col-md-4
          .form-group
            = f.select :order_type, order_types.map { |o| [o.to_s, o.id] }, {}, {placeholder: t('.order_type'), class: 'form-control selectize'}
        .col-sm-6.col-md-4
          .form-group
            = f.select :status, Order.statuses.map { |s| [Order.human_attribute_value(:status, s), s] }, {include_blank: t('.status')}, {class: 'form-control selectize'}
        .col-sm-6.col-md-4
          .form-group
            .input-group.input-daterange{data: {provide: 'datepicker', 'date-format': 'yyyy-mm-dd', 'date-language': I18n.locale, 'date-orientation': 'bottom'}}
              = f.search_field :since_date, autocomplete: 'off', placeholder: t('.since_date'), class: 'form-control'
              %span.input-group-addon= icon('caret-right')
              = f.search_field :until_date, autocomplete: 'off', placeholder: t('.until_date'), class: 'form-control'
        .col-sm-6.col-md-8
          .form-group
            = f.search_field :keyword, autocomplete: 'off', placeholder: t('.keyword'), class: 'form-control'
        .col-sm-6.col-md-4
          .form-group
            = f.search_field :payment_number, autocomplete: 'off', placeholder: t('.payment_number'), class: 'form-control'
        .col-sm-6.col-md-5
          .form-group
            = f.select :customer_id, @customers.map { |c| [c.to_s, c.id] }, {include_blank: t('.customer')}, {class: 'form-control selectize'}
        .col-sm-6.col-md-5
          .form-group
            = f.select :user_id, @users.map { |u| [u.to_s, u.id] }, {include_blank: t('.user')}, {class: 'form-control selectize'}
        .col-sm-6.col-md-2
          .form-group
            = f.submit t('actions.search'), class: 'btn btn-block btn-primary'

app/views/admin/orders/_shipments.html.haml
%ul.list-group
- @order.shipments.active.each do |shipment|
  %li.list-group-item
    - if shipment.shipped?
      .badge= l(shipment.shipped_at.to_date)
    %strong= shipment
    = shipment.shipping_method

app/views/admin/orders/_table.html.haml
.table-responsive
  %table.table.table-hover
    %thead
      %tr
        %th.col-min
        %th.col-xs-1= col(Order, :number)
        %th.col-xs-1= col(Order, :completed_at)
        - if current_store.b2b_sales?
          %th.col-xs-2= col(Order, :shipping_installation_at)
        %th= col(Order, :customer_id)
        %th.col-xs-1.text-right= col(Order, :items)
        %th.col-xs-1.text-right= col(Order, :grand_total)
        %th.col-xs-2.actions

    %tbody
      = render partial: 'admin/orders/row', collection: orders, as: :order

app/views/admin/orders/approve.js.haml
$('#orders-inspect-modal').modal('hide');
$("##{dom_id(@order)}").replaceWith("#{j render partial: 'admin/orders/row', object: @order, as: :order}");

app/views/admin/orders/conclude.js.haml
$('#orders-inspect-modal').modal('hide');
$("##{dom_id(@order)}").replaceWith("#{j render partial: 'admin/orders/row', object: @order, as: :order}");

app/views/admin/orders/edit.html.haml
.page-header
  = link_to back_path_for(@order), class: 'btn btn-default' do
    = icon('chevron-circle-left', t('actions.back'))
  = link_to admin_order_path(@order), class: 'btn btn-primary' do
    = icon('info-circle', t('actions.show'))
  %h1
    = @order.order_type
    %span.small
      = @order.to_s
      = surround('[', ']') { @order.inventory.to_s }

= render partial: 'instructions'
= life_pro_tip @order

.row
  .col-lg-4
    = render partial: 'form', locals: {locked: false}

  .col-lg-8
    = tab_set 'order-side', class: 'nav-justified nav-sm' do
      = nav_tab 'shipments', title(Shipment, count: 2), default: true
      = nav_tab 'order-items', title(OrderItem, count: 2)
      = nav_tab 'payments', title(Payment, count: 2)
      = nav_tab 'history', t('admin.activities.title')

    .tab-content
      = tab_pane 'shipments', default: true do
        - if !@order.cancelled?
          = render partial: 'admin/order_items/pending', object: @order, as: :order
        %h4.visible-print-block= t('.shipped_items')
        = render partial: 'admin/shipments/list', object: @order, as: :order, locals: {locked: @order.concluded?}

      = tab_pane 'order-items' do
        %h4.visible-print-block= title(OrderItem, count: 2)
        - if @order.editable_items?
          = render partial: 'admin/order_items/edit_table', object: @order, as: :order
        - else
          = render partial: 'admin/order_items/table', object: @order, as: :order

      = tab_pane 'payments', class: 'hidden-print' do
        = render partial: 'admin/payments/table', object: @order, as: :order

      = tab_pane 'history' do
        #context-activities.hidden-print{data: {url: context_admin_activities_path(format: :js), gid: @order.to_global_id}}

:coffee
  $('#context-activities').fetch_context()

#shipments-edit-modal.modal{data: {backdrop: 'static'}}

- if @order.approved? && @order.track_shipments?
  :coffee
    $('[href="#tab-shipments"]').tab 'show'
- else
  :coffee
    $('[href="#tab-order-items"]').tab 'show'

- if @order.editable_items?
  - content_for :secondary_nav do
    = render partial: 'admin/orders/edit', object: @order, as: :order

app/views/admin/orders/incoming.html.haml
.page-header
  - if current_user.can_create?(Order, at: current_store)
    = link_to new_admin_order_path, class: 'btn btn-primary' do
      = icon('plus', t('admin.orders.index.new_order'))
  = link_to admin_order_items_path, class: 'btn btn-default' do
    = icon('list', t('.order_items'))
  %h1= icon('inbox', t('.title'))

= render partial: 'search', locals: {url: incoming_admin_orders_path, order_types: current_group.incoming_order_types}

= render partial: 'admin/orders/table', object: @orders, as: :orders
= paginate @orders

#orders-inspect-modal.modal{data: {backdrop: 'static'}}

app/views/admin/orders/new.html.haml
.page-header
  = link_to admin_orders_path, class: 'btn btn-default' do
    = icon('chevron-circle-left', t('actions.back'))
  %h1
    = t('.new_order')

.row
  = render partial: 'form_for_new', object: @order, as: :order

app/views/admin/orders/outgoing.html.haml
.page-header
  - if current_user.can_create?(Order, at: current_store)
    = link_to new_admin_order_path, class: 'btn btn-primary' do
      = icon('plus', t('admin.orders.index.new_order'))
  %h1= icon('paper-plane', t('.title'))

= render partial: 'search', locals: {url: outgoing_admin_orders_path, order_types: current_group.outgoing_order_types}

= render partial: 'admin/orders/table', object: @orders, as: :orders
= paginate @orders