config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints(host: ENV['STELLAR_HOST']) do
    resource :onboarding do
      get :frontend
      get :backend
      get :admin
      post 'validate/:step', action: :validate, as: :validate
    end
    get '/', to: 'account#index'
    get '/get-started', to: 'account#onboarding', as: :get_started
  end

  root 'store#index'

  # Catch error conditions early.
  match '(errors)/:status', to: 'errors#show',
    constraints: {status: /\d{3}/},
    defaults: {status: '500'},
    via: :all

  # Point-of-sale interface.
  #namespace :pos do
  #  root 'main#index'
  #  resources :orders do
  #    resources :order_items, shallow: true
  #  end
  #  resources :products do
  #    get :query, on: :collection
  #  end
  #end

  # Mount stripe engine at /stripe
  mount Stripe::Engine => '/stripe'

  resources :orders do
    resources :order_items, shallow: true
    member do
      get :select
      get :preview
      patch :claim
      get :duplicate
    end
  end
  resource :profile, only: [:show, :edit, :update]

  # Catch bona fide storefront urls that are not accessible via slugs.
  get  '/store', to: 'store#index', as: :store
  get  '/store/lookup', to: 'store#lookup', as: :lookup
  get  '/cart/quote/:recipient', to: 'store#quote', as: :send_quote
  get  '/cart/delete',  to: 'store#delete_cart', as: :delete_cart
  post '/cart/activate_code', to: 'store#activate_code', as: :activate_code
  post '/correspondence/mail_form', to: 'correspondence#mail_form', as: :mail_form

  # Routes for the checkout process:
  #
  # 1) set order type
  post '/checkout/:order_id/order_type', to: 'checkout#order_type', as: :order_type
  # 2) enter checkout process
  get  '/checkout/:order_id', to: 'checkout#checkout',  as: :checkout
  # 3) select a shipping method
  get  '/checkout/:order_id/shipping_method/:method_id', to: 'checkout#shipping_method', as: :shipping_method
  # 4) create a shipment
  post '/checkout/:order_id/ship', to: 'checkout#ship', as: :ship
  # 5) get payment methods
  get  '/checkout/:order_id/payment_methods', to: 'checkout#payment_methods', as: :payment_methods
  # 6) enter payment information
  get  '/checkout/:order_id/pay/:method', to: 'checkout#pay', as: :pay
  # 7) verify credit card payment or return from online payment
  post '/checkout/:order_id/verify', to: 'checkout#verify', as: :verify
  get  '/checkout/:order_id/return', to: 'checkout#return', as: :return
  # 7b) handle online payment notify if the user failed to return herself
  get  '/checkout/:order_id/notify', to: 'checkout#notify', as: :notify
  # 7c) confirm order when payment is not collected
  post '/checkout/:order_id/confirm', to: 'checkout#confirm', as: :confirm
  # 8) show a receipt
  get  '/checkout/:order_id/receipt', to: 'checkout#receipt', as: :receipt

  # Product specific routes.
  post '/product/:product_id/order', to: 'store#order_product', as: :order_product
  post '/product/:product_id/set_order_amount', to: 'store#set_order_amount', as: :set_order_amount

  # Favorite manipulation.
  get    '/store/favorites', to: 'store#show_favorites', as: :favorites
  get    '/store/favorites/:product_id', to: 'store#show_favorite', as: :show_favorite
  post   '/store/favorites/:product_id', to: 'store#add_favorite', as: :add_favorite
  delete '/store/favorites/:product_id', to: 'store#remove_favorite', as: :remove_favorite

  # Category, tag, department, promotion, and product views.
  get '/category/:category_id', to: 'store#show_category', as: :show_category
  get '/category/:category_id/order', to: 'store#show_category_order', as: :show_category_order
  get '/tag/:tag_id', to: 'store#show_tag', as: :show_tag
  get '/department/:department_id', to: 'store#show_department', as: :show_department
  get '/promotion/:promotion_id', to: 'store#show_promotion', as: :show_promotion
  get '/product/:product_id(/:category_id)', to: 'store#show_product', as: :show_product
  get '/products/promoted', to: 'store#show_promoted_products', as: :show_promoted_products

  # These routes can be reached via /:slug
  get '/front', to: 'store#front', as: :front
  get '/cart',  to: 'store#cart',  as: :cart

  # Content consumer actions.
  get '/content/feed', to: 'content#feed', as: :content_feed

  # Koala actions
  get 'koala/feed'

  # If we get here, the url is seen as a slug of a page. If the page
  # is internal, its slug will match one of the above routes.
  get '/:slug', to: 'store#show_page', as: :show_page, slug: /[a-z0-9_-]+/

  namespace :admin do
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    get '/reports', to: 'reports#index', as: :reports
    get '/reports/inventory', to: 'reports#inventory', as: :inventory_report
    get '/reports/sales', to: 'reports#sales', as: :sales_report
    get '/reports/sales_tax', to: 'reports#sales_tax', as: :sales_tax_report
    get '/reports/purchases', to: 'reports#purchases', as: :purchases_report
    get '/reports/product/:product_id/sales', to: 'reports#product_sales', as: :product_sales

    resources :stores do
      resources :hostnames, shallow: true
      resources :pictures, shallow: true
      resource :style
    end
    resources :subscriptions
    resources :groups do
      resources :users, only: [:index, :new, :create] do
        patch :join, on: :member
      end
      member do
        patch :make_default
        get :select_categories
        patch :toggle_category
      end
      post :reorder, on: :collection
    end
    resources :users, except: [:index, :new, :create] do
      resources :roles, only: [] do
        patch :toggle, on: :member
      end
    end
    resources :policies do
      patch :accept, on: :member
    end
    resources :tax_categories do
      post :reorder, on: :collection
    end
    resources :inventories do
      post :reorder, on: :collection
    end
    resources :inventory_items do
      resources :inventory_entries, shallow: true, only: :create
      collection do
        get :query
        get :refresh
      end
    end
    resources :inventory_checks do
      resources :inventory_check_items, shallow: true do
        member do
          patch :approve
          patch :discard
        end
      end
      member do
        patch :complete
        get :resolve
        patch :conclude
      end
    end
    resources :properties do
      post :reorder, on: :collection
    end
    resources :tags do
      resources :pictures, shallow: true
    end
    resources :transfers do
      resources :transfer_items, shallow: true
      patch :complete, on: :member
    end
    resources :activities, only: [:index, :show] do
      get :context, on: :collection
    end
    resources :departments do
      resources :pictures, shallow: true
      post :reorder, on: :collection
    end
    resources :categories do
      resources :pictures, shallow: true
      post :rearrange, on: :collection
      get :reorder_products, on: :member
    end
    resources :pages do
      resources :pictures, shallow: true
      resources :sections, shallow: true do
        resources :pictures
        resources :columns do
          resources :pictures
          resources :segments do
            resources :pictures
            resources :documents
            member do
              get :settings
              patch :modify
              get :copy
            end
            collection do
              post :reorder
              post :paste
            end
          end
          member do
            get :settings
            patch :modify
          end
        end
        member do
          get :preload
          get :settings
          patch :modify
        end
        post :reorder, on: :collection
      end
      member do
        get :layout
        post :duplicate
      end
      post :rearrange, on: :collection
    end
    resources :images do
      get :select, on: :member
    end
    resources :products do
      resources :pictures, shallow: true
      resources :documents, shallow: true
      resources :product_properties, shallow: true
      resources :alternate_prices
      resources :inventory_items, shallow: true
      resources :component_entries, shallow: true do
        post :reorder, on: :collection
      end
      resources :requisite_entries, shallow: true do
        post :reorder, on: :collection
      end
      collection do
        get :query
        get 'pricing(/:group_id)', action: :pricing, as: :pricing
        post :reorder
        post :upload_file
      end
      member do
        post :add_requisite_entries
        post :duplicate
        patch 'set_price(/:group_id)', action: :set_price, as: :set_price
        patch :make_primary
      end
    end
    resources :promotions do
      resources :promoted_items, shallow: true
      resources :pictures, shallow: true
      post :add_products, on: :member
      post :add_categories, on: :member
    end
    resources :order_types
    resources :shipping_methods do
      resources :pictures, shallow: true
    end
    resources :orders do
      resources :pictures, shallow: true
      resources :order_items, shallow: true, except: [:index]
      resources :shipments, shallow: true do
        member do
          patch :refresh
          patch :complete
          get :label
        end
      end
      collection do
        get :incoming
        get :outgoing
      end
      member do
        get :forward
        get :preview
        patch :approve
        get :review
        patch :conclude
      end
    end
    resources :order_items, only: [:index]

    post '/hostnames/reorder', to: 'hostnames#reorder', as: :reorder_hostnames
    post '/pictures/reorder', to: 'pictures#reorder', as: :reorder_pictures
    post '/documents/reorder', to: 'documents#reorder', as: :reorder_documents
    post '/pictures/delete', to: 'pictures#delete', as: :delete_picture
    post '/documents/delete', to: 'documents#delete', as: :delete_document
  end

  if Rails.env.production?

app/controllers/admin/stores_controller.rb
class Admin::StoresController < AdminController

  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /admin/stores
  # GET /admin/stores.json
  def index
    authorize_action_for Store, at: current_store
    query = saved_search_query('store', 'admin_store_search')
    @search = StoreSearch.new(query)
    @stores = @search.results
  end

  # GET /admin/stores/1
  # GET /admin/stores/1.json
  def show
    authorize_action_for @store, at: current_store
  end

  # GET /admin/stores/new
  def new
    authorize_action_for Store, at: current_store
    @store = Store.new(locale: I18n.default_locale, country: Country.default)
    @store.tax_categories.build
  end

  # GET /admin/stores/1/edit
  def edit
    authorize_action_for @store, at: current_store
  end

  # POST /admin/stores
  # POST /admin/stores.json
  def create
    authorize_action_for Store, at: current_store
    @store = Store.new(store_params.merge(Store.default_settings))

    respond_to do |format|
      if @store.save
        track @store
        format.html { redirect_to edit_admin_store_path(@store),
          notice: t('.notice', store: @store) }
        format.json { render :show, status: :created, location: admin_store_path(@store) }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    authorize_action_for @store, at: current_store

    respond_to do |format|
      if @store.update(store_params)
        track @store
        format.html { redirect_to admin_store_path(@store),
          notice: t('.notice', store: @store) }
        format.json { render :show, status: :ok, location: admin_store_path(@store) }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(
        :portal, :name, :locale, :country_code, :shipping_origin,
        :admit_guests, :disable_mail, :custom_smtp_settings,
        :disable_shipment_transfers, :tracking_code, :maps_api_key,
        :facebook_access_token, :facebook_pixel_id,
        :tawkto_site_id, :pbw_api_key, :pbw_private_key,
        :quotation_template_id, :footer_page_id,
        :csv_encoding, :csv_product_code,
        :csv_trade_price, :csv_retail_price, :csv_inventory_amount,
        :order_xml_path, :erp_number, :vat_number, :order_sequence,
        :theme, :main_nav_lookup, :detach_menu, :fancy_cart,
        :cart_promotion, :favorites, :category_order, :masonry,
        :smtp_address, :smtp_port,
        :smtp_user_name, :smtp_password,
        :smtp_authentication, :smtp_enable_starttls_auto,
        tax_categories_attributes: [
          :name, :rate, :included_in_retail
        ]
      )
    end
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/store_helper.rb
module StoreHelper

  # Generates a product url that can be in another store
  # if the current store is a portal.
  def product_url(product, category = nil)
    if current_store.portal?
      host = product.store.hostname_at(current_store)
      show_product_url(product, host: host.to_s)
    else
      show_product_path(product, category)
    end
  end

  def fuzzy_amount(amount)
    amount > 25 ? t('number.more_than', number: 25) : amount
  end

  # Returns a potentially fuzzy stock reading for given product.
  # If no inventory is given, fuzziness is applied to infinity.
  # See Product#available.
  def product_stock(inventory, product)
    available = product.available(inventory, nil)
    inventory.nil? || inventory.fuzzy? ? fuzzy_amount(available) : available
  end

  def money(amount)
    return nil if amount.nil?
    humanized_money_with_symbol(amount)
  end

  def fancy_price(price)
    return nil if price.nil?
    amount = incl_tax? ? price.with_tax : price.sans_tax
    sep = amount.decimal_mark
    units, subunits = humanized_money(amount).split sep
    capture do
      concat units
      concat content_tag(:span, sep, class: 'sep')
      concat content_tag(:span, subunits, class: 'cents')
      concat currency_symbol
    end
  end

  def fancy_price_range(from, to)
    if from == to
      fancy_price(from)
    else
      capture do
        concat fancy_price(from)
        concat '–'
        concat fancy_price(to)
      end
    end
  end

  # Displays a fancy price tag with a single final price,
  # or dual special/regular prices.
  def price_tag(final_price, regular_price = nil)
    content_tag(:span, class: regular_price && 'special-price') do
      concat fancy_price(final_price)
      if regular_price
        concat content_tag(:span, class: 'regular-price') { fancy_price(regular_price) }
      end
    end
  end

  # Displays a fancy price range from two final prices.
  def price_range(from, to)
    content_tag(:span, class: 'price-range') do
      fancy_price_range(from, to)
    end
  end

  def unit_pricing_string(price, quantity, unit)
    unless quantity.zero?
      capture do
        concat price_tag(price / quantity)
        concat '/'
        concat unit
      end
    end
  end
end

app/views/admin/stores/_form.html.haml
= bootstrap_form_for [:admin, @store] do |f|
  = tab_set 'store-main', class: 'panel-tabs' do
    = nav_tab 'store-admin', col(Store, :admin), default: true
    = nav_tab 'store-appearance', col(Store, :appearance)
    = nav_tab 'store-apis', col(Store, :apis)
    = nav_tab 'store-files', col(Store, :files)
    - if current_user_has_role?(:superuser)
      = nav_tab 'store-superuser', col(Store, :superuser)
    - if @store.new_record?
      = nav_tab 'store-new-tax-category', col(Store, :new_tax_category)

  .panel.panel-default.tabbed-panel
    .panel-body
      .tab-content
        = tab_pane 'store-admin', default: true do
          %fieldset{disabled: locked}
            = f.form_group do
              = f.check_box :portal
            = f.form_group do
              = f.check_box :admit_guests
            = f.form_group do
              = f.check_box :category_order
            = f.form_group do
              = f.check_box :favorites
            %hr
            = f.text_field :name, required: true
            .row
              .col-md-6
                = f.select :locale, Store.locale_options, {}, {class: 'selectize'}
              .col-md-6
                = f.select :country_code, Store.country_options, {}, {class: 'selectize'}
            - unless @store.new_record?
              %hr
              = f.select :quotation_template_id, @store.template_options, {include_blank: true}, {class: 'selectize'}
        = tab_pane 'store-appearance' do
          %fieldset{disabled: locked}
            = f.form_group do
              = f.check_box :main_nav_lookup
            = f.form_group do
              = f.check_box :detach_menu
            = f.form_group do
              = f.check_box :masonry
            = f.form_group do
              = f.check_box :fancy_cart
            = f.form_group do
              = f.check_box :cart_promotion
            .row
              .col-md-8
                = f.select :theme, Store.theme_options, {}, {class: 'selectize'}
              - unless locked || @store.new_record?
                .col-md-4
                  .form-group
                    %label.control-label= t('.edit_style')
                    = link_to edit_admin_store_style_path(@store), class: 'btn btn-default btn-block', remote: true do
                      = icon('paint-brush', t('actions.edit'))
            %hr
            = f.select :footer_page_id, Page.options_for_select(@store.pages.primary) { |p, l| [indent(p.to_s, l), p.id] }, {include_blank: t('.default_footer')}, {class: 'selectize'}
        = tab_pane 'store-apis' do
          %fieldset{disabled: locked}
            = f.form_group do
              = f.check_box :disable_mail
            = f.form_group do
              = f.check_box :custom_smtp_settings
          #custom-smtp-settings.collapse{class: @store.custom_smtp_settings? && 'in'}
            %fieldset{disabled: locked}
              .row
                .col-sm-8
                  = f.text_field :smtp_address
                .col-sm-4
                  = f.text_field :smtp_port
              .row
                .col-sm-4
                  = f.text_field :smtp_user_name
                .col-sm-4
                  = f.text_field :smtp_password
                .col-sm-4
                  = f.select :smtp_authentication, [nil, :plain, :login, :cram_md5], {}, {class: 'selectize'}
              = f.check_box :smtp_enable_starttls_auto
          %hr
          %fieldset{disabled: locked}
            .row
              .col-md-6
                = f.text_field :tracking_code
              .col-md-6
                = f.text_field :maps_api_key
            = f.text_field :shipping_origin
            %hr
            .row
              .col-md-6
                = f.text_field :facebook_access_token
              .col-md-6
                = f.text_field :facebook_pixel_id
            %hr
            = f.text_field :tawkto_site_id
          %fieldset{disabled: locked}
            %legend= PaymentGateway::Paybyway.model_name.human
            .row
              .col-md-6
                = f.text_field :pbw_api_key
              .col-md-6
                = f.text_field :pbw_private_key
        = tab_pane 'store-files' do
          %fieldset{disabled: locked}
            %legend= col(Store, :product_csv)
            = f.text_field :csv_encoding
            .row
              .col-md-6
                = f.text_field :csv_product_code
              .col-md-6
                = f.text_field :csv_trade_price
            .row
              .col-md-6
                = f.text_field :csv_retail_price
              .col-md-6
                = f.text_field :csv_inventory_amount
          %fieldset{disabled: locked}
            %legend= col(Store, :order_xml)
            = f.text_field :order_xml_path
        - if current_user_has_role?(:superuser)
          = tab_pane 'store-superuser' do
            %fieldset{disabled: locked}
              = f.text_field :vat_number
              .row
                .col-md-6
                  = f.number_field :erp_number
                - unless @store.new_record?
                  .col-md-6
                    = f.text_field :slug, readonly: true, help: t('.slug_help_html')
              = f.text_field :order_sequence, help: t('.order_sequence_help_html')
              = f.form_group do
                = f.check_box :disable_shipment_transfers
        - if @store.new_record?
          = tab_pane 'store-new-tax-category' do
            = f.fields_for :tax_categories do |ff|
              %fieldset{disabled: locked}
                = ff.text_field :name, required: true
                = ff.text_field :rate, append: '%', class: 'text-right', required: true
                = ff.form_group do
                  = ff.check_box :included_in_retail

      - unless locked
        %fieldset.actions.fixed
          .container
            = f.primary

:coffee
  persist_tabs 'store-main'

  $('#store_custom_smtp_settings').on 'change', (e) ->
    if $(e.target).is ':checked'
      $('#custom-smtp-settings').collapse 'show'
    else
      $('#custom-smtp-settings').collapse 'hide'

app/views/admin/stores/_search.html.haml
.panel.panel-info
  .panel-heading
    %h4.panel-title= t('actions.search')
  .panel-body
    = form_for @search, url: admin_stores_path, method: :get do |f|
      .row
        .col-sm-3
          .form-group
            = f.text_field :name, placeholder: col(Store, :name), class: 'form-control'
        .col-sm-3
          .form-group
            = f.text_field :hostname, placeholder: col(Store, :hostnames), class: 'form-control'
        .col-sm-4
          .form-group
            = f.select :domain, Hostname.domain.map { |h| [h.to_s, h.id] }, {}, {multiple: true, placeholder: col(Hostname, :parent_hostname_id), class: 'selectize'}
        .col-sm-2
          .form-group
            = f.submit t('actions.search'), class: 'btn btn-block btn-primary'

app/views/admin/stores/_table.html.haml
.table-responsive
  %table.table.table-hover
    %thead
      %tr
        %th.col-min
        %th.col-xs-3= col(Store, :name)
        %th= col(Store, :network)
        %th.actions

    %tbody
      - @stores.each do |store|
        %tr[store]{class: store.portal? && 'info text-info'}
          %td= picture_variant_tag store.cover_picture, :icon
          %td= store.name
          %td
            - store.store_portals.each do |portal|
              = bootstrap_label(portal)
            - store.member_stores.each do |member|
              = bootstrap_label(member, appearance: :primary)
          %td.actions
            - if current_store != store && store.hostnames.any?
              = link_to icon('bookmark', t('actions.select')), admin_stores_url(host: (store.hostname_at(current_store) || store.primary_host).to_s), class: 'btn btn-default btn-sm'
            = link_to icon('info', t('actions.show')), admin_store_path(store), class: 'btn btn-default btn-sm'
            - if current_user.can_update?(store, at: current_store)
              = link_to icon('edit', t('actions.edit')), edit_admin_store_path(store), class: 'btn btn-default btn-sm'

app/views/admin/stores/edit.html.haml
.page-header
  - if current_user.can_read?(Store, at: current_store)
    = link_to admin_stores_path, class: 'btn btn-default' do
      = icon('chevron-circle-left', t('actions.back'))
  = link_to admin_store_path(@store), class: 'btn btn-primary' do
    = icon('info-circle', t('actions.show'))
  %h1
    = picture_variant_tag @store.cover_picture, :icon
    = @store

.row
  .col-md-6
    = render partial: 'form', locals: {locked: false}

  .col-md-6
    = tab_set 'store-side', class: 'nav-justified nav-sm' do
      = nav_tab 'hostnames', col(Store, :hostnames), default: true
      = nav_tab 'images', col(Store, :images)

    .tab-content
      = tab_pane 'hostnames', default: true do
        = render partial: 'admin/hostnames/edit_table', object: @store, as: :store
      = tab_pane 'images' do
        = render partial: 'admin/pictures/edit_collection', object: @store, as: :pictureable

#style-modal.modal{data: {backdrop: 'static'}}

:coffee
  persist_tabs 'store-side'

app/views/admin/stores/index.html.haml
.page-header
  - if current_user.can_create?(Store, at: current_store)
    = link_to new_admin_store_path, class: 'btn btn-primary' do
      = icon('plus', t('.new_store'))
  %h1= icon('paw', title(Store, count: 2))

= render partial: 'search'
= render partial: 'table'

app/views/admin/stores/new.html.haml
.page-header
  = link_to admin_stores_path, class: 'btn btn-default' do
    = icon('chevron-circle-left', t('actions.back'))
  %h1
    = t('.new_store')

.row
  .col-md-6
    = render partial: 'form', locals: {locked: false}

app/views/admin/stores/show.html.haml
.page-header
  - if current_user.can_read?(Store, at: current_store)
    = link_to admin_stores_path, class: 'btn btn-default' do
      = icon('chevron-circle-left', t('actions.back'))
  - if current_user.can_update?(@store, at: current_store)
    = link_to edit_admin_store_path(@store), class: 'btn btn-primary' do
      = icon('pencil-square', t('actions.edit'))
  %h1
    = picture_variant_tag @store.cover_picture, :icon
    = @store

.row
  .col-md-6
    = render partial: 'form', locals: {locked: true}

  .col-md-6
    = tab_set 'store-side', class: 'nav-justified nav-sm' do
      = nav_tab 'hostnames', col(Store, :hostnames), default: true
      = nav_tab 'images', col(Store, :images)

    .tab-content
      = tab_pane 'hostnames', default: true do
        = render partial: 'admin/hostnames/table', object: @store, as: :store
      = tab_pane 'images' do
        = render partial: 'admin/pictures/collection', object: @store, as: :pictureable

:coffee
  persist_tabs 'store-side'