config/routes.rb
  constraints(host: ENV['STELLAR_HOST']) do
    resource :onboarding do
      get :frontend
      get :backend
      get :admin
      post 'validate/:step', action: :validate, as: :validate
    end
    get '/', to: 'account#index'
    get '/get-started', to: 'account#onboarding', as: :get_started
  end

  root 'store#index'

  # Catch error conditions early.
  match '(errors)/:status', to: 'errors#show',
    constraints: {status: /\d{3}/},
    defaults: {status: '500'},
    via: :all

  # Point-of-sale interface.
  #namespace :pos do
  #  root 'main#index'
  #  resources :orders do
  #    resources :order_items, shallow: true
  #  end
  #  resources :products do
  #    get :query, on: :collection
  #  end
  #end

  # Mount stripe engine at /stripe
  mount Stripe::Engine => '/stripe'

  resources :orders do
    resources :order_items, shallow: true
    member do
      get :select
      get :preview
      patch :claim
      get :duplicate
    end
  end
  resource :profile, only: [:show, :edit, :update]

  # Catch bona fide storefront urls that are not accessible via slugs.
  get  '/store', to: 'store#index', as: :store
  get  '/store/lookup', to: 'store#lookup', as: :lookup
  get  '/cart/quote/:recipient', to: 'store#quote', as: :send_quote
  get  '/cart/delete',  to: 'store#delete_cart', as: :delete_cart
  post '/cart/activate_code', to: 'store#activate_code', as: :activate_code
  post '/correspondence/mail_form', to: 'correspondence#mail_form', as: :mail_form

  # Routes for the checkout process:
  #
  # 1) set order type
  post '/checkout/:order_id/order_type', to: 'checkout#order_type', as: :order_type
  # 2) enter checkout process
  get  '/checkout/:order_id', to: 'checkout#checkout',  as: :checkout
  # 3) select a shipping method
  get  '/checkout/:order_id/shipping_method/:method_id', to: 'checkout#shipping_method', as: :shipping_method
  # 4) create a shipment
  post '/checkout/:order_id/ship', to: 'checkout#ship', as: :ship
  # 5) get payment methods
  get  '/checkout/:order_id/payment_methods', to: 'checkout#payment_methods', as: :payment_methods
  # 6) enter payment information
  get  '/checkout/:order_id/pay/:method', to: 'checkout#pay', as: :pay
  # 7) verify credit card payment or return from online payment
  post '/checkout/:order_id/verify', to: 'checkout#verify', as: :verify
  get  '/checkout/:order_id/return', to: 'checkout#return', as: :return
  # 7b) handle online payment notify if the user failed to return herself
  get  '/checkout/:order_id/notify', to: 'checkout#notify', as: :notify
  # 7c) confirm order when payment is not collected
  post '/checkout/:order_id/confirm', to: 'checkout#confirm', as: :confirm
  # 8) show a receipt
  get  '/checkout/:order_id/receipt', to: 'checkout#receipt', as: :receipt

  # Product specific routes.
  post '/product/:product_id/order', to: 'store#order_product', as: :order_product
  post '/product/:product_id/set_order_amount', to: 'store#set_order_amount', as: :set_order_amount

  # Favorite manipulation.
  get    '/store/favorites', to: 'store#show_favorites', as: :favorites
  get    '/store/favorites/:product_id', to: 'store#show_favorite', as: :show_favorite
  post   '/store/favorites/:product_id', to: 'store#add_favorite', as: :add_favorite
  delete '/store/favorites/:product_id', to: 'store#remove_favorite', as: :remove_favorite

  # Category, tag, department, promotion, and product views.
  get '/category/:category_id', to: 'store#show_category', as: :show_category
  get '/category/:category_id/order', to: 'store#show_category_order', as: :show_category_order
  get '/tag/:tag_id', to: 'store#show_tag', as: :show_tag
  get '/department/:department_id', to: 'store#show_department', as: :show_department
  get '/promotion/:promotion_id', to: 'store#show_promotion', as: :show_promotion
  get '/product/:product_id(/:category_id)', to: 'store#show_product', as: :show_product
  get '/products/promoted', to: 'store#show_promoted_products', as: :show_promoted_products

  # These routes can be reached via /:slug
  get '/front', to: 'store#front', as: :front
  get '/cart',  to: 'store#cart',  as: :cart

  # Content consumer actions.
  get '/content/feed', to: 'content#feed', as: :content_feed

  # Koala actions
  get 'koala/feed'

  # If we get here, the url is seen as a slug of a page. If the page
  # is internal, its slug will match one of the above routes.
  get '/:slug', to: 'store#show_page', as: :show_page, slug: /[a-z0-9_-]+/

  namespace :admin do
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    get '/reports', to: 'reports#index', as: :reports
    get '/reports/inventory', to: 'reports#inventory', as: :inventory_report
    get '/reports/sales', to: 'reports#sales', as: :sales_report
    get '/reports/sales_tax', to: 'reports#sales_tax', as: :sales_tax_report
    get '/reports/purchases', to: 'reports#purchases', as: :purchases_report
    get '/reports/product/:product_id/sales', to: 'reports#product_sales', as: :product_sales

    resources :stores do
      resources :hostnames, shallow: true
      resources :pictures, shallow: true
      resource :style
    end
    resources :subscriptions
    resources :groups do
      resources :users, only: [:index, :new, :create] do
        patch :join, on: :member
      end
      member do
        patch :make_default
        get :select_categories
        patch :toggle_category
      end
      post :reorder, on: :collection
    end
    resources :users, except: [:index, :new, :create] do
      resources :roles, only: [] do
        patch :toggle, on: :member
      end
    end
    resources :policies do
      patch :accept, on: :member
    end
    resources :tax_categories do
      post :reorder, on: :collection
    end
    resources :inventories do
      post :reorder, on: :collection
    end
    resources :inventory_items do
      resources :inventory_entries, shallow: true, only: :create
      collection do
        get :query
        get :refresh
      end
    end
    resources :inventory_checks do
      resources :inventory_check_items, shallow: true do
        member do
          patch :approve
          patch :discard
        end
      end
      member do
        patch :complete
        get :resolve
        patch :conclude
      end
    end
    resources :properties do
      post :reorder, on: :collection
    end
    resources :tags do
      resources :pictures, shallow: true
    end
    resources :transfers do
      resources :transfer_items, shallow: true
      patch :complete, on: :member
    end
    resources :activities, only: [:index, :show] do
      get :context, on: :collection
    end
    resources :departments do
      resources :pictures, shallow: true
      post :reorder, on: :collection
    end
    resources :categories do
      resources :pictures, shallow: true
      post :rearrange, on: :collection
      get :reorder_products, on: :member
    end
    resources :pages do
      resources :pictures, shallow: true
      resources :sections, shallow: true do
        resources :pictures
        resources :columns do
          resources :pictures
          resources :segments do
            resources :pictures
            resources :documents
            member do
              get :settings
              patch :modify
              get :copy
            end
            collection do
              post :reorder
              post :paste
            end
          end
          member do
            get :settings
            patch :modify
          end
        end
        member do
          get :preload
          get :settings
          patch :modify
        end
        post :reorder, on: :collection
      end
      member do
        get :layout
        post :duplicate
      end
      post :rearrange, on: :collection
    end
    resources :images do
      get :select, on: :member
    end
    resources :products do
      resources :pictures, shallow: true
      resources :documents, shallow: true
      resources :product_properties, shallow: true
      resources :alternate_prices
      resources :inventory_items, shallow: true
      resources :component_entries, shallow: true do
        post :reorder, on: :collection
      end
      resources :requisite_entries, shallow: true do
        post :reorder, on: :collection
      end
      collection do
        get :query
        get 'pricing(/:group_id)', action: :pricing, as: :pricing
        post :reorder
        post :upload_file
      end
      member do
        post :add_requisite_entries
        post :duplicate
        patch 'set_price(/:group_id)', action: :set_price, as: :set_price
        patch :make_primary
      end
    end
    resources :promotions do
      resources :promoted_items, shallow: true
      resources :pictures, shallow: true
      post :add_products, on: :member
      post :add_categories, on: :member
    end
    resources :order_types
    resources :shipping_methods do
      resources :pictures, shallow: true
    end
    resources :orders do
      resources :pictures, shallow: true
      resources :order_items, shallow: true, except: [:index]
      resources :shipments, shallow: true do
        member do
          patch :refresh
          patch :complete
          get :label
        end
      end
      collection do
        get :incoming
        get :outgoing
      end
      member do
        get :forward
        get :preview
        patch :approve
        get :review
        patch :conclude
      end
    end
    resources :order_items, only: [:index]

    post '/hostnames/reorder', to: 'hostnames#reorder', as: :reorder_hostnames
    post '/pictures/reorder', to: 'pictures#reorder', as: :reorder_pictures
    post '/documents/reorder', to: 'documents#reorder', as: :reorder_documents
    post '/pictures/delete', to: 'pictures#delete', as: :delete_picture
    post '/documents/delete', to: 'documents#delete', as: :delete_document
  end

  if Rails.env.production?
    match "*any", via: :all, to: redirect('/404')
  end

app/models/image.rb
class Image < ApplicationRecord

  STYLES = %w{icon thumbnail matchbox postcard technical shoebox presentational laptop lightbox}

  paginates_per 12

  include Authority::Abilities
  include Trackable

  #---
  has_many :pictures, dependent: :destroy
  belongs_to :store

  has_attached_file :attachment,
    styles: {
      lightbox:       '1920x1200>',
      laptop:         '1440x900>',
      presentational: '1000x600>',
      shoebox:        '720x480>',
      technical:      '400x400>',
      postcard:       '300x300>',
      matchbox:       '200x200>',
      thumbnail:      '75x75>',
      icon:           '25x25#',
    },
    convert_options: {
      all:            '-colorspace sRGB -strip',
      lightbox:       '-quality 80',
      laptop:         '-quality 80',
      presentational: '-quality 80',
      shoebox:        '-quality 80',
      technical:      '-quality 80',
      postcard:       '-quality 80',
      matchbox:       '-quality 70',
      thumbnail:      '-quality 70',
      icon:           '-quality 70',
    },
    adapter_options: {
      hash_digest: Digest::SHA256
    }
  before_post_process :resize_bitmaps

  default_scope { order(created_at: :desc) }

  delegate :url, to: :attachment

  #---
  validates_attachment :attachment,
    content_type: {
      content_type: [
        %r{\Aimage/(bmp|jpeg|jpg|png|x-png|svg)},
      ]
    }

  #---
  def is_vector?
    !!(attachment_content_type =~ /\/svg/)
  end

  def is_bitmap?
    !is_vector?
  end

  # Image dimensions courtesy of FastImage, cached.
  def dimensions(style = :original)
    @dimensions ||= {}
    return {} unless is_bitmap? && File.exist?(attachment.path(style))
    @dimensions[style] ||= [:width, :height].zip(FastImage.size(attachment.path(style))).to_h
  end

  def portrait?
    return nil unless is_bitmap?
    dimensions[:height] > dimensions[:width]
  end

  def landscape?
    !portrait?
  end

  def to_s
    attachment_file_name.humanize
  end

  private
    def resize_bitmaps
      is_bitmap?
    end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController

  # GET /admin/images
  def index
    query = saved_search_query('image', 'admin_image_search')
    @search = ImageSearch.new(query.merge(search_constrains))
    @images = @search.results.page(params[:page])

    respond_to :js
  end

  # GET /admin/images/1/edit.js
  def edit
    @image = current_store.images.find(params[:id])

    respond_to :js
  end

  # POST /admin/images
  def create
    @image = current_store.images.build(image_params)

    respond_to do |format|
      if @image.save
        track @image
        format.json { render :show } # for dropzone
      else
        format.html { render json: {error: t('.error')} }
        format.json { render json: {error: @image.errors.full_messages.join(', ')}, status: 400 }
      end
    end
  end

  # DELETE /admin/images/1
  def destroy
    @image = current_store.images.find(params[:id])
    authorize_action_for @image, at: current_store

    respond_to do |format|
      if @image.destroy
        track @image
        format.js
      end
    end
  end

  # GET /admin/images/1/select
  def select
    @image = current_store.images.find(params[:id])
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:attachment)
    end

    # Restrict searching to images in current store.
    def search_constrains
      {store: current_store}
    end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_browser.html.haml
- grid_columns ||= 3

.grid.thumbnail-grid{class: "grid-columns-#{grid_columns}", style: 'opacity: 0;'}
  - images.each do |image|
    .grid-item[image]{data: {id: image.id}}
      = link_to select_admin_image_path(image), class: 'thumbnail', remote: true do
        %figure= image_variant_tag image, :matchbox
      .grid-widgets
        .pull-right
          - if current_user.can_delete?(image, at: current_store)
            = link_to icon('remove'), admin_image_path(image), remote: true, method: :delete, class: 'btn btn-xs btn-danger'
      .badge
        .truncate{title: image.attachment_file_name}
          = image.attachment_file_name

.row
  .col-xs-8
    = paginate images, window: 2, remote: true
  .col-xs-4.search
    = form_for @search, url: admin_images_path, method: :get, remote: true do |f|
      .form-group
        .input-group
          = f.search_field 'keyword', autocomplete: 'off', class: 'form-control', placeholder: t('.search')
          .input-group-btn
            %button.btn.btn-default{type: 'submit'}= icon('search')

app/views/admin/images/_dropzone.html.haml
= form_for [:admin, Image.new], html: {multipart: true, class: 'dropzone'} do |f|
  .fallback
    = f.file_field :attachment
    = f.submit class: 'btn btn-primary'

:coffee
  Dropzone.autoDiscover = false
  $('#new_image').dropzone
    dictDefaultMessage: "#{I18n.t('dropzone.upload_images')}"
    paramName: 'image[attachment]'
    init: ->
      @on 'success', (file, image) ->
        $.get '/admin/images'
        $.get '/admin/images/' + image.id + '/select'
      @on 'complete', (file) ->
        this.removeFile file

app/views/admin/images/_edit.html.haml
= link_to edit_admin_image_path(image), remote: true, class: ['btn btn-default', image.is_vector? && 'disabled'] do
  = icon('crop', t('.button'))

app/views/admin/images/_editor.html.haml
#image-editor
  %nav.navbar.navbar-inverse
    %ul.nav.navbar-nav.navbar-right
      %li.danger
        %a#editor-cancel{role: 'button'}
          = icon('close', t('actions.cancel'), class: 'fa-fw')
      %li.success
        %a#editor-save{role: 'button'}
          = icon('save', t('actions.save'), class: 'fa-fw')

  .canvas
    = image_variant_tag image, :original

:coffee
  $image = $('#image-editor > .canvas > img')
  editor = new Cropper $image[0]
  editor.cleanUp = ->
    editor.destroy()
    $.magnificPopup.close()

  $('#editor-save').on 'click', ->
    canvas = editor.getCroppedCanvas
      maxWidth: 4096
      maxHeight: 4096
      imageSmoothingQuality: 'medium'
    canvas.toBlob (blob) ->
      data = new FormData()
      data.append 'image[attachment]', blob, '#{image.attachment_file_name}'
      $.ajax
        url: '#{admin_images_path}'
        type: 'POST'
        data: data
        processData: false
        contentType: false
        success: (response) ->
          editor.cleanUp()
          $.ajax
            type: 'GET'
            url: '#{admin_images_path}'
            success: ->
              $('#picture-modal').modal 'show';
              $.get response.select_url
        error: ->
          editor.cleanUp()
          $('#picture-modal').modal 'show';
    , '#{image.attachment_content_type}', 0.8

  $('#editor-cancel').on 'click', ->
    editor.cleanUp()
    $('#picture-modal').modal 'show';

app/views/admin/images/_preview.html.haml
= image_variant_tag image, :postcard

app/views/admin/images/destroy.js.haml
$('#picture_image_id').val(null);
$('#image-preview').html('');
$('#image-edit-link').html('');
$('##{dom_id(@image)}').fadeOut(200, function() { this.remove(); });

app/views/admin/images/edit.js.haml
$('#picture-modal').modal('hide');
$.magnificPopup.open({items: {src: "#{j render partial: 'admin/images/editor', object: @image, as: :image}"}, mainClass: 'mfp-fullscreen', alignTop: true, overflowY: 'hidden', modal: true});

app/views/admin/images/index.js.haml
$('#image-browser').html("#{j render partial: 'admin/images/browser', object: @images, as: :images, locals: {grid_columns: 6}}");
$('#image-browser > .grid').imagesLoaded(function () { $('#image-browser > .grid').animateCss('fadeIn', function () { $('#image-browser > .grid').css({opacity: 1}); }); });

app/views/admin/images/select.js.haml
$('#picture_image_id').val(#{@image.id});
$('#image-preview').html("#{j render partial: 'admin/images/preview', object: @image, as: :image}");
$('#image-edit-link').html("#{j render partial: 'admin/images/edit', object: @image, as: :image}");